
all:
	pdflatex paper
	pdflatex paper
	bibtex paper
	pdflatex paper
	pdflatex paper

clean:
	/bin/rm -f paper.pdf *.dvi *.aux *.ps *~ *.log *.out *.ent
	/bin/rm -f *.lot *.lof *.toc *.blg *.bbl url.sty
